name: Check NGDB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.6, 3.7, 3.8, 3.9, "3.10" ]

    steps:

    - name: Check out the NGDB code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pipenv
      run: python -m pip install --upgrade pipenv wheel

    - name: Patch Pipfile for Python ${{ matrix.python-version }}
      run: |
        head -n -1 Pipfile > Pipfile.tmp
        echo "python_version = \"${{ matrix.python-version }}\"" >> Pipfile.tmp
        mv Pipfile.tmp Pipfile
        rm Pipfile.lock
        pipenv lock
        pipenv --python ${{ matrix.python-version }}
        make setup

    - name: Install dependencies
      run: make setup

    - name: Lint
      run: make lint

    - name: Type check
      run: make stricttypecheck

    - name: Test
      run: make test

### checks.yml ends here
